# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings accessible in the templates via {{ site.myvariable }}.
title: Aditi Mohanty | Front-End Engineer, Bangalore, India.
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/gh-pages-playground" # the subpath of your site, e.g. /blog
url: "http://aditimohanty.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - script

assets:
  gzip: true
  sources:
  - "css"
